import fs from 'fs';
import path from 'path';
import sharp from 'sharp';

const WEBP_QUALITY = 72;
const CONTENT_WIDTHS = [400, 760, 1000];
const HERO_WIDTHS = [640, 960];
const LOGO_SIZE = 256;

const imagesDir = path.resolve('src/assets/images');
const heroDir = path.resolve('public/hero');
const publicImagesDir = path.resolve('public/images');
const publicDir = path.resolve('public');
const manifestPath = path.resolve('src/data/imageManifest.ts');

function slugFromFilename(filename) {
  return path.basename(filename, path.extname(filename));
}

async function writeWebpVariant(inputPath, outputPath, width) {
  await fs.promises.mkdir(path.dirname(outputPath), { recursive: true });
  await sharp(inputPath)
    .rotate()
    .resize({
      width,
      withoutEnlargement: true,
    })
    .webp({ quality: WEBP_QUALITY })
    .toFile(outputPath);

  const meta = await sharp(outputPath).metadata();
  return {
    width: meta.width ?? width,
    height: meta.height ?? width,
    bytes: fs.statSync(outputPath).size,
  };
}

async function generateResponsiveSet(inputPath, outputDir, widths) {
  const variants = {};

  for (const width of widths) {
    const outputPath = path.join(outputDir, `${width}.webp`);
    variants[width] = await writeWebpVariant(inputPath, outputPath, width);
  }

  const largest = widths[widths.length - 1];
  const meta = variants[largest];
  const totalKb = Object.values(variants).reduce((sum, v) => sum + v.bytes, 0) / 1024;

  console.log(
    `${path.basename(inputPath)} → ${path.relative(process.cwd(), outputDir)} (${totalKb.toFixed(0)}KB total across ${widths.length} sizes)`
  );

  return {
    basePath: `/${path.relative(publicDir, outputDir).replace(/\\/g, '/')}`,
    widths,
    width: meta.width,
    height: meta.height,
  };
}

async function writeLogoAssets(inputPath) {
  const logoWebp = path.join(imagesDir, 'secret_rooftop_logo_1787736669250.webp');
  await sharp(inputPath)
    .rotate()
    .resize(LOGO_SIZE, LOGO_SIZE, { fit: 'cover', withoutEnlargement: true })
    .webp({ quality: WEBP_QUALITY })
    .toFile(`${logoWebp}.tmp`);
  fs.renameSync(`${logoWebp}.tmp`, logoWebp);

  await sharp(logoWebp)
    .resize(48, 48, { fit: 'cover' })
    .png({ compressionLevel: 9 })
    .toFile(path.join(publicDir, 'favicon.png'));
  await sharp(logoWebp)
    .resize(180, 180, { fit: 'cover' })
    .png({ compressionLevel: 9 })
    .toFile(path.join(publicDir, 'apple-touch-icon.png'));

  const logoMeta = await sharp(logoWebp).metadata();
  console.log(`logo: ${Math.round(fs.statSync(logoWebp).size / 1024)}KB webp (${logoMeta.width}x${logoMeta.height})`);
  console.log('favicon.png and apple-touch-icon.png generated from logo');

  return {
    src: logoWebp,
    width: logoMeta.width ?? LOGO_SIZE,
    height: logoMeta.height ?? LOGO_SIZE,
  };
}

function writeManifest(manifest) {
  const body = `// Generated by scripts/compress-images.mjs — do not edit manually.
export type ImageVariantSet = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  fullSrc: string;
};

type ManifestEntry = {
  basePath: string;
  widths: number[];
  width: number;
  height: number;
};

const MANIFEST: Record<string, ManifestEntry> = ${JSON.stringify(manifest, null, 2)};

function buildSet(slug: string, defaultWidth = 760): ImageVariantSet {
  const entry = MANIFEST[slug];
  if (!entry) {
    throw new Error(\`Missing image manifest entry for "\${slug}"\`);
  }

  const srcSet = entry.widths
    .map((w) => \`\${entry.basePath}/\${w}.webp \${w}w\`)
    .join(', ');
  const pick = entry.widths.includes(defaultWidth) ? defaultWidth : entry.widths[entry.widths.length - 1];
  const full = entry.widths[entry.widths.length - 1];

  return {
    src: \`\${entry.basePath}/\${pick}.webp\`,
    srcSet,
    width: entry.width,
    height: entry.height,
    fullSrc: \`\${entry.basePath}/\${full}.webp\`,
  };
}

export function getContentImage(slug: string): ImageVariantSet {
  return buildSet(slug, 760);
}

export function getHeroPoster(): ImageVariantSet {
  return buildSet('rooftop-drone-poster', 960);
}

export const IMAGE_SLUGS = Object.keys(MANIFEST);
`;

  fs.writeFileSync(manifestPath, body);
  console.log(`Wrote ${path.relative(process.cwd(), manifestPath)}`);
}

const manifest = {};

const contentFiles = fs
  .readdirSync(imagesDir)
  .filter((f) => /\.(jpe?g|png)$/i.test(f) && !f.includes('logo'));

for (const file of contentFiles) {
  const slug = slugFromFilename(file);
  manifest[slug] = await generateResponsiveSet(
    path.join(imagesDir, file),
    path.join(publicImagesDir, slug),
    CONTENT_WIDTHS
  );
}

if (fs.existsSync(heroDir)) {
  const heroSource = path.join(heroDir, 'rooftop-drone-poster.jpg');
  if (fs.existsSync(heroSource)) {
    manifest['rooftop-drone-poster'] = await generateResponsiveSet(
      heroSource,
      path.join(heroDir, 'rooftop-drone-poster'),
      HERO_WIDTHS
    );

    // Keep a flat fallback file for older links and JSON-LD.
    fs.copyFileSync(
      path.join(heroDir, 'rooftop-drone-poster', '960.webp'),
      path.join(heroDir, 'rooftop-drone-poster.webp')
    );
    const heroJpegTmp = path.join(heroDir, 'rooftop-drone-poster.jpg.tmp');
    await sharp(heroSource)
      .rotate()
      .resize({ width: 960, withoutEnlargement: true })
      .jpeg({ quality: 70, mozjpeg: true })
      .toFile(heroJpegTmp);
    fs.renameSync(heroJpegTmp, path.join(heroDir, 'rooftop-drone-poster.jpg'));
  }
}

const logoPath = path.join(imagesDir, 'secret_rooftop_logo_1787736669250.jpg');
if (fs.existsSync(logoPath)) {
  await writeLogoAssets(logoPath);
}

writeManifest(manifest);
