// Generated by scripts/compress-images.mjs — do not edit manually.
export type ImageVariantSet = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  fullSrc: string;
};

type ManifestEntry = {
  basePath: string;
  widths: number[];
  width: number;
  height: number;
};

const MANIFEST: Record<string, ManifestEntry> = {
  "bar-van-day": {
    "basePath": "/images/bar-van-day",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "bar-van-evening": {
    "basePath": "/images/bar-van-evening",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 1000,
    "height": 1500
  },
  "cheese-board": {
    "basePath": "/images/cheese-board",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "dj-booth": {
    "basePath": "/images/dj-booth",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "pizza-slice": {
    "basePath": "/images/pizza-slice",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "rooftop-flower-barrel": {
    "basePath": "/images/rooftop-flower-barrel",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "rooftop-lounge-seating": {
    "basePath": "/images/rooftop-lounge-seating",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 1000,
    "height": 1500
  },
  "rooftop-signage": {
    "basePath": "/images/rooftop-signage",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "rooftop-stage-lanterns": {
    "basePath": "/images/rooftop-stage-lanterns",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "rooftop-sunset-stage": {
    "basePath": "/images/rooftop-sunset-stage",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 1000,
    "height": 1500
  },
  "table-lounge-cushions": {
    "basePath": "/images/table-lounge-cushions",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "table-skyline-sunset": {
    "basePath": "/images/table-skyline-sunset",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 1000,
    "height": 1500
  },
  "table-string-lights": {
    "basePath": "/images/table-string-lights",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "wine-cheese-bar": {
    "basePath": "/images/wine-cheese-bar",
    "widths": [
      400,
      760,
      1000
    ],
    "width": 866,
    "height": 1300
  },
  "rooftop-drone-poster": {
    "basePath": "/hero/rooftop-drone-poster",
    "widths": [
      640,
      960
    ],
    "width": 900,
    "height": 1350
  }
};

function buildSet(slug: string, defaultWidth = 760): ImageVariantSet {
  const entry = MANIFEST[slug];
  if (!entry) {
    throw new Error(`Missing image manifest entry for "${slug}"`);
  }

  const srcSet = entry.widths
    .map((w) => `${entry.basePath}/${w}.webp ${w}w`)
    .join(', ');
  const pick = entry.widths.includes(defaultWidth) ? defaultWidth : entry.widths[entry.widths.length - 1];
  const full = entry.widths[entry.widths.length - 1];

  return {
    src: `${entry.basePath}/${pick}.webp`,
    srcSet,
    width: entry.width,
    height: entry.height,
    fullSrc: `${entry.basePath}/${full}.webp`,
  };
}

export function getContentImage(slug: string): ImageVariantSet {
  return buildSet(slug, 760);
}

export function getHeroPoster(): ImageVariantSet {
  return buildSet('rooftop-drone-poster', 960);
}

export const IMAGE_SLUGS = Object.keys(MANIFEST);
